"""US-009 output layer and block naming."""

OUTPUT_ELECTRICAL_LAYER_NAME = "Cambre_Electrical"
LEGACY_ELECTRICAL_LAYER_NAME = "INSTALACION_ELECTRICA"
DEFAULT_OUTLET_BLOCK_NAME = "CAMBRE_OUTLET"
DEFAULT_LAYER_COLOR_ACI = 3
OUTLET_BLOCK_RADIUS = 100.0
