#!/usr/bin/env bash
# Copy Supabase (and related) vars from repo root .env into apps/api and apps/web.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/common.sh
source "$ROOT/scripts/lib/common.sh"

write_api_env() {
  local dest="$ROOT/apps/api/.env"
  cat >"$dest" <<EOF
# Generated by scripts/sync-dev-env.sh — edit root .env instead.
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
API_PORT=${API_PORT:-3001}
CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173,http://localhost:5174}
SIGNED_URL_TTL_SECONDS=${SIGNED_URL_TTL_SECONDS:-3600}
PUBLIC_WEB_URL=${PUBLIC_WEB_URL:-http://localhost:5174}
INVITE_TOKEN_TTL_MS=${INVITE_TOKEN_TTL_MS:-604800000}
INVITE_RATE_LIMIT_WINDOW_MS=${INVITE_RATE_LIMIT_WINDOW_MS:-3600000}
INVITE_RATE_LIMIT_MAX=${INVITE_RATE_LIMIT_MAX:-30}
EOF
  echo "Wrote $dest"
}

write_web_env() {
  local dest="$ROOT/apps/web/.env"
  cat >"$dest" <<EOF
# Generated by scripts/sync-dev-env.sh — edit root .env instead.
VITE_SUPABASE_URL=${SUPABASE_URL:-}
VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
EOF
  echo "Wrote $dest"
}

main() {
  load_root_env
  if [[ -z "${SUPABASE_URL:-}" || -z "${SUPABASE_ANON_KEY:-}" ]]; then
    echo "SUPABASE_URL and SUPABASE_ANON_KEY must be set in $ROOT/.env" >&2
    exit 1
  fi
  write_api_env
  write_web_env
}

main "$@"
